name: azlir_portfolio
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  http: ^1.1.0
  material_design_icons_flutter: ^7.0.7296
  photo_view: ^0.14.0
  riverpod: ^2.3.6
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
